### ISSUE TITLE
NameError: global name 'logger' is not defined

### ISSUE THREAD

**Issue by giantpune** [slazarov/python-bittrex-autosell#2]
```sh
$ pba --coins XVG,BTC
Traceback (most recent call last):
  File "/home/j/c/python-bittrex-autosell/bin/pba", line 11, in <module>
    sys.exit(main())
  File "/home/j/c/python-bittrex-autosell/local/lib/python2.7/site-packages/python_bittrex_autosell/main.py", line 122, in main
    coins = get_coins(args.coins)
  File "/home/j/c/python-bittrex-autosell/local/lib/python2.7/site-packages/python_bittrex_autosell/main.py", line 50, in get_coins
    logger.error(ERROR_COIN_NUMBER)
NameError: global name 'logger' is not defined
```

**Comment by slazarov** [comment]
How did you install the package?

**Comment by giantpune** [comment]
I installed with pip install like the readme suggests.  I think the error is caused by it trying to use the logger variable before it's been declared.

**Comment by slazarov** [comment]
Hi, please reinstall. 

Additionally, you are specifying only two tickers, they should be at least three, check the example usage.
